Version 4.68
PaylineByMonext/payline-java-sdk pull request #14
Opened 2021-10-15 10:13 UTC by vpietri-tbd

2021-11-17 13:58 UTC, thomasmonext requested changes

2021-11-17 13:58 UTC, thomasmonext commented on src/main/java/com/payline/ws/wrapper/WalletPayment.java
> +        final Authentication3DSecure authentication3DSecure, final String version, final Buyer buyer, final Owner owner, final String media, ContractNumberWalletList contractNumberWalletList, final S
il manquele final sur contractNumberWalletList

2021-11-17 13:58 UTC, thomasmonext commented on src/main/java/com/payline/ws/wrapper/WalletPayment.java
> +            return this.updateWallet(wallet, contractNumber, privateDataList,
Il manque les paramètres **null**, je ne pense pas que le code compile

2021-11-17 13:58 UTC, thomasmonext commented on src/main/java/com/payline/ws/wrapper/WalletPayment.java
> +            return this.updateWebWallet(walletId, privateDataList, notificationURL, returnURL,
il manque les null values je pense

2021-11-17 13:58 UTC, thomasmonext commented on src/main/java/com/payline/ws/wrapper/WalletPayment.java
> +        final String Cardind, final String version, final String  updateOwnerDetails, ContractNumberWalletList contractNumberWalletList) {
Ne devait-i lpas y avoir un **contractNumber** d'ajouter en paramètre ?

2021-11-23 08:28 UTC, thomasmonext commented
@vpietri-tbd pouvez-vous faire un rebase de votre branch agence-tbd:version_4.68 par rapport  notre master svp.
Il semble qu'il y ait des conflits.

Sinon pour les modifications c'est ok.

2021-11-23 08:30 UTC, thomasmonext commented
![image](https://user-images.githubusercontent.com/48686647/142991599-cafdc24c-ea25-4d26-9fae-021e2fe040e7.png)

2021-11-29 14:44 UTC, vpietri-tbd commented
@thomasmonext Bonjour, nous avons fait un merge pour récupérer les modifications de Gerald.

Le code que nous livrons passe systématiquement la phase de compilation et ensuite de validation via Sonaqube (pour les paramètres null manquant sur UpdateWalletResponse, la signature de la méthode appelée étant la même que la méthode appelante cela aurait pu être une récursivité).

2021-12-01 08:18 UTC, merged